# Generated by Django 3.2 on 2021-08-02 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210802_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='tasktime',
            field=models.DurationField(),
        ),
    ]
